### PR TITLE
rootfs: Use the correct location for CNI config

### PR DESCRIPTION
**Pull request by tomdee**
New default (for k8s 1.4) set by this PR
https://github.com/kubernetes/kubernetes/pull/32151

### CODE REVIEW

**Comment by s-urbaniak** [comment]
@tomdee Thanks! Short question from my side: won't this break k8s 1.3 which expects the config to be present in the old directory!?

**Comment by tomdee** [comment]
@s-urbaniak Hmmm, good point. What do you think a good solution would be to maintain backwards compatibility? Is it possible to just symlink the two directories? Or maybe minikube and localkube could be updated to ensure that the kubelet gets started with the right parameters to use this directory?

**Comment by s-urbaniak** [comment]
I'd say for now we should go with a symlink, and then on a follow-up issue
architect a general CNI solution with arbitrary plugins.

**Comment by tomdee** [comment]
Any hints on how to do a symlink - I have virtually no buildroot experience :smile:

**Comment by s-urbaniak** [comment]
No problem ;) I'm ooo right now, but will prep, and merge a symlink
tomorrow, so don't sweat it ;)

**Comment by tomdee** [comment]
After poking around a bit I thought I could add it to https://github.com/coreos/minikube-iso/blob/master/package/cni-bin/cni-bin.mk or is that too hacky?

**Comment by s-urbaniak** [comment]
@tomdee mhhh ... I'd leave this in the rootfs overlay, making a simple relative symlink, see #25

**Comment by s-urbaniak** [comment]
Closing in favor of #25

**Pull request closed without merging**
